### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'taskRewardName')

### ISSUE THREAD

**Issue by Ljzd-PRO** [treasunew/SillyLib#3]
ksjsbmixed.js
```
TypeError: Cannot read properties of null (reading 'taskRewardName')
    at _0x9d8dda.luckdrawTasksReward (/ql/scripts/raw_JavaScript_ksjsbenhance.js:814:120)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _0x9d8dda.luckdrawTasks (/ql/scripts/raw_JavaScript_ksjsbenhance.js:791:63)
    at async /ql/scripts/raw_JavaScript_ksjsbenhance.js:960:9
```

**Comment by treasunew** [comment]
@Ljzd-PRO 脚本已经失效了

**Comment by Ljzd-PRO** [comment]
好的。是所有的都失效了吗

**Comment by treasunew** [comment]
@Ljzd-PRO 对，有新脚本，收费，就不放出来了

**Comment by Ljzd-PRO** [comment]
好的
